export const primary = '#fff'
export const secondary = 'orange'
export const black = '#000'
export const silver = '#C0C0C0'
export const darkGrey = '#999999'
export const darkRed = '#b61b33'
export const lightGrey = '#D3D3D3'
export const lightLightGrey = '#F0F0F0'